kind: pipeline
name: default

steps:
  - name: build
    image: plugins/hugo
    settings:
      source: home
      output: public
  - name: deploy
    image: cschlosser/drone-ftps
    settings:
      hostname: tb.gaesdonck.info:21
      clean_dir: true
      secure: false
      dest_dir: html
      src_dir: /home/public
    environment:
      FTP_USERNAME:
        from_secret: ftpuser
      FTP_PASSWORD:
        from_secret: ftppass
